<a href="https://colab.research.google.com/github/VaibhavKapil1819/ml-daily-notes/blob/main/scikitlearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SCIKIT LEARN FULL COURSE**

In [2]:
from sklearn.datasets import  load_breast_cancer
from sklearn.model_selection import train_test_split #function to split data into training portion
from sklearn.preprocessing import StandardScaler #function for scaling data
from sklearn.neighbors import KNeighborsClassifier

In [7]:
data = load_breast_cancer(return_X_y=True)

Loading Data

In [10]:
X, y= load_breast_cancer(return_X_y=True)

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

Split data

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

Scaling the data

In [13]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Training the data

In [14]:
knn = KNeighborsClassifier()
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

Prediction

In [15]:
print(knn.score(X_test_scaled,y_test))

0.9298245614035088


The code above  does the following:

1.  **Loads some data:** It gets a dataset about breast cancer. Think of it like a table with information about different tumors.
2.  **Splits the data:** It divides the data into two parts: one for "training" the computer model and one for "testing" how well it learned.
3.  **Scales the data:** It adjusts the numbers in the data so they are all in a similar range. This helps the model work better.
4.  **Trains a model:** It uses a method called K-Nearest Neighbors (KNN) to teach the computer how to classify tumors as either malignant or benign based on the training data.
5.  **Makes predictions and checks accuracy:** It uses the trained model to predict the type of tumor for the test data and then checks how many of those predictions were correct. The number you saw (like 0.929...) is the percentage of correct predictions.

This is a basic example to show you how scikit-learn can be used for this kind of task. We'll go into much more detail about each of these steps and other things you can do with scikit-learn later!

### **DATA LOADING**

In [ ]:
from sklearn.datasets import  load_breast_cancer

In [16]:
data = load_breast_cancer()

In [17]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [21]:
x1 = data.data
y= data.target

In [23]:
x1

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [24]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

Scikit-learn provides flexibility in how you load datasets.

*   When you use `return_X_y=True`, the function returns two separate arrays: `X` containing the features (the data you use to make predictions) and `y` containing the target variable (what you are trying to predict).
*   When you use `as_frame=True`, the function returns a Bunch object, and you can access the data as a pandas DataFrame using the `.frame` attribute. This DataFrame includes both the features and the target variable in a single structure, which can be convenient for initial data exploration and manipulation using pandas.

In [25]:
X2,y2 = load_breast_cancer(return_X_y=True)

In [29]:
X2

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [30]:
y2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [33]:
frame1 =load_breast_cancer(as_frame=True).frame

In [34]:
frame1

mean radius  mean texture  ...  worst fractal dimension  target
0          17.99         10.38  ...                  0.11890       0
1          20.57         17.77  ...                  0.08902       0
2          19.69         21.25  ...                  0.08758       0
3          11.42         20.38  ...                  0.17300       0
4          20.29         14.34  ...                  0.07678       0
..           ...           ...  ...                      ...     ...
564        21.56         22.39  ...                  0.07115       0
565        20.13         28.25  ...                  0.06637       0
566        16.60         28.08  ...                  0.07820       0
567        20.60         29.33  ...                  0.12400       0
568         7.76         24.54  ...                  0.07039       1

[569 rows x 31 columns]

###  Loading data

In scikit-learn, you can easily load built-in datasets for practice. These datasets are like pre-packaged tables of information that we can use to learn and experiment with machine learning techniques. We've loaded two examples here: the Breast Cancer dataset and the California Housing dataset.

In [35]:
from sklearn.datasets import fetch_california_housing

In [36]:
frame2= fetch_california_housing(as_frame=True).frame

In [37]:
frame2

MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
0      8.3252      41.0  6.984127  ...     37.88    -122.23        4.526
1      8.3014      21.0  6.238137  ...     37.86    -122.22        3.585
2      7.2574      52.0  8.288136  ...     37.85    -122.24        3.521
3      5.6431      52.0  5.817352  ...     37.85    -122.25        3.413
4      3.8462      52.0  6.281853  ...     37.85    -122.25        3.422
...       ...       ...       ...  ...       ...        ...          ...
20635  1.5603      25.0  5.045455  ...     39.48    -121.09        0.781
20636  2.5568      18.0  6.114035  ...     39.49    -121.21        0.771
20637  1.7000      17.0  5.205543  ...     39.43    -121.22        0.923
20638  1.8672      18.0  5.329513  ...     39.43    -121.32        0.847
20639  2.3886      16.0  5.254717  ...     39.37    -121.24        0.894

[20640 rows x 9 columns]

## **SPLITTING DATA**

### Why Splitting Data is Necessary

Imagine you're studying for a test. If you only practiced with the exact same questions that will be on the test, you might do well, but would you truly understand the material and be able to answer new questions?

Splitting our data is similar. We divide our dataset into two main parts:

1.  **Training Data:** This is the data we use to "teach" our machine learning model. The model learns patterns and relationships from this data.
2.  **Testing Data:** This is data that the model has *never* seen before. We use this data to evaluate how well our trained model performs on new, unseen examples.

By testing on separate data, we get a more realistic idea of how our model will perform in the real world, where it will encounter new data. If we trained and tested on the same data, we might overestimate how good our model is because it has simply memorized the answers.

So, splitting the data helps us ensure our model can generalize and make accurate predictions on new data, not just the data it was trained on.

In [53]:
# Common imports
import numpy as np
from sklearn.model_selection import (
    train_test_split, KFold, RepeatedKFold, StratifiedKFold, RepeatedStratifiedKFold,
    ShuffleSplit, StratifiedShuffleSplit,
    GroupKFold, GroupShuffleSplit, StratifiedGroupKFold,
    LeaveOneOut, LeavePOut, LeaveOneGroupOut, LeavePGroupsOut,
    PredefinedSplit, TimeSeriesSplit, check_cv
)

# Sample dataset
X = np.arange(40).reshape(20, 2)   # 20 samples, 2 features
y = np.array([0, 1, 0, 1, 0, 1])  # binary target
groups = [1, 1, 2, 2, 3, 3]       # group labels


🔹 1. Train-Test Split

The simplest way to split data into train and test sets.

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print("Train indices:", X_train)
print("Test indices:", X_test)


Train indices: [[10 11]
 [ 4  5]
 [ 8  9]
 [ 6  7]]
Test indices: [[0 1]
 [2 3]]


🔹 2. KFold

Splits into k folds, cycling each as test set.

In [55]:
kf = KFold(n_splits=5, shuffle=False)
for fold, (train, test) in enumerate(kf.split(X), 1):
    print(f"Fold {fold} → Train: {train}, Test: {test}")


Fold 1 → Train: [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19], Test: [0 1 2 3]
Fold 2 → Train: [ 0  1  2  3  8  9 10 11 12 13 14 15 16 17 18 19], Test: [4 5 6 7]
Fold 3 → Train: [ 0  1  2  3  4  5  6  7 12 13 14 15 16 17 18 19], Test: [ 8  9 10 11]
Fold 4 → Train: [ 0  1  2  3  4  5  6  7  8  9 10 11 16 17 18 19], Test: [12 13 14 15]
Fold 5 → Train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], Test: [16 17 18 19]


🔹 3. RepeatedKFold

Repeats K-Fold multiple times with different splits.

In [56]:
rkf = RepeatedKFold(n_splits=3, n_repeats=2, random_state=42)
for train, test in rkf.split(X):
    print("Train:", train, "Test:", test)


Train: [ 2  3  4  6  7  9 10 12 13 14 16 18 19] Test: [ 0  1  5  8 11 15 17]
Train: [ 0  1  4  5  6  7  8 10 11 12 14 15 17] Test: [ 2  3  9 13 16 18 19]
Train: [ 0  1  2  3  5  8  9 11 13 15 16 17 18 19] Test: [ 4  6  7 10 12 14]
Train: [ 0  1  2  3  6  7  8  9 10 11 13 17 18] Test: [ 4  5 12 14 15 16 19]
Train: [ 0  1  4  5  8 11 12 14 15 16 17 18 19] Test: [ 2  3  6  7  9 10 13]
Train: [ 2  3  4  5  6  7  9 10 12 13 14 15 16 19] Test: [ 0  1  8 11 17 18]


🔹 4. StratifiedKFold

Keeps class distribution balanced across folds.

In [50]:
skf = StratifiedKFold(n_splits=3)
for train, test in skf.split(X, y):
    print("Train:", train, "Test:", test)


Train: [2 3 4 5] Test: [0 1]
Train: [0 1 4 5] Test: [2 3]
Train: [0 1 2 3] Test: [4 5]


🔹 6. ShuffleSplit

Random train/test splits multiple times.

In [51]:
ss = ShuffleSplit(n_splits=3, test_size=0.3, random_state=42)
for train, test in ss.split(X):
    print("Train:", train, "Test:", test)


Train: [5 2 4 3] Test: [0 1]
Train: [1 2 5 4] Test: [3 0]
Train: [0 3 5 2] Test: [4 1]


🔹 7. StratifiedShuffleSplit

Random splits but preserves class balance.

In [52]:
sss = StratifiedShuffleSplit(n_splits=3, test_size=0.3, random_state=42)
for train, test in sss.split(X, y):
    print("Train:", train, "Test:", test)


Train: [2 5 0 3] Test: [1 4]
Train: [1 0 4 3] Test: [2 5]
Train: [0 5 2 3] Test: [4 1]
